steps:
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/web-juanfrancisco:$BUILD_ID", "."]

  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["push",  "gcr.io/$PROJECT_ID/web-juanfrancisco:$BUILD_ID"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'web-juanfrancisco'
    - '--image'
    - 'gcr.io/$PROJECT_ID/web-juanfrancisco:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '80'